services:
  - type: web
    name: fastapi-backend
    rootDir: frontend/
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 127.0.0.1 --port 8000"
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: nextjs-frontend
    rootDir: backend/
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
        
